PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX cccev: <http://data.europa.eu/m8g/>

CONSTRUCT {
  ?s ?p ?o
}
WHERE {
  graph <http://data.europa.eu/a4g/resource/2024/00665930_2024> {
       ?s ?p ?o
  }
}
